name: CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  qa-test-train:
    runs-on: ubuntu-latest
    env:
      PYTHONHASHSEED: '42'
      PYTHONPATH: ${{ github.workspace }}/src
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint
        run: ruff check .
      - name: Tests
        run: pytest -q --disable-warnings --maxfail=1
      - name: Quick train & save artifacts
        run: python -m cli.train_and_eval
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-and-metrics
          path: |
            artifacts/model.joblib
            artifacts/metrics.json
            artifacts/input_schema.json
