name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Train (deterministic)
        env:
          PYTHONHASHSEED: '42'
        run: |
          python -m src.cli.train_and_eval
          echo "Tag: $GITHUB_REF_NAME" || true
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: |
          IMAGE=ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          docker build -t $IMAGE .
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
      - name: Smoke test container
        run: |
          docker run -d -p 8000:8000 --name svc $IMAGE
          sleep 3
          curl -f http://localhost:8000/health
          curl -s -X POST http://localhost:8000/predict -H 'Content-Type: application/json' -d @assets/sample_payload.json
          docker rm -f svc
      - name: Push image
        run: docker push $IMAGE
      - name: GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: See CHANGELOG.md for details.
          files: artifacts/metrics.json
